---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: diadhuit
# description will be included in the image's metadata
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      keys:
        - https://repo.protonvpn.com/fedora-44-stable/public_key.asc
      nonfree: negativo17
    install:
      packages:
        - brave-origin
        - https://repo.protonvpn.com/fedora-%OS_VERSION%-stable/protonvpn-stable-release/protonvpn-stable-release-1.0.4-1.noarch.rpm
        - https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm  # Change when stable released
        - https://proton.me/download/PassDesktop/linux/x64/ProtonPass.rpm
        - https://proton.me/download/meet/linux/ProtonMeet-desktop.rpm
        - https://proton.me/download/authenticator/linux/ProtonAuthenticator.rpm
        - proton-vpn-gnome-desktop
        - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm  # Temporary
        - https://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_x86_64.rpm  # On trial
        - yakuake
        - steam
        - starship
        - fastfetch
        - haruna
        - gwenview
        - okular
        - kalk
        - kcolorchooser
        - ktorrent
        - mediawriter
        - elisa
        - kolourpaint
        - ksystemlog
        - krdc
        - kclock
        - kweather
        - kget
        - akregator
        - openmw # temporary
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user
        # If no repo information is specified, Flathub will be used by default
        install:
          - com.github.k4zmu2a.spacecadetpinball

  - type: brew

  - type: os-release
    properties:
      ID: diadhuit
      ID_LIKE: fedora
      NAME: DiaDhuit
      PRETTY_NAME: DiaDhuit Linux
      DEFAULT_HOSTNAME: DiaDhuit

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
